### ISSUE TITLE
Be able to make changes

### ISSUE THREAD

**Issue by negebauer** [julien-vidal/github-label-manager#3]
When a label is already created [this](../) could, for example, change it's color

**Comment by julien-vidal** [comment]
By default, idea was to just always replace, but the idea could be cool to implement.

What do you think if I add an option on copy/import for changing the strategy on how glm will manage existing labels ?

noOption : replace (current behavior)
OptionSet : Update if non present

Option name to define of course !

**Comment by negebauer** [comment]
That would be terrific
It would be very useful for managing labels in existing projects (where replacing would delete the labels from issues)
Also to change color, if someone wants to do that

Something like
`glm --update`

**Comment by julien-vidal** [comment]
Humm I'm not totally sure to understand your needs, I come back to your example :
`glm --update`

The `--update` should be used with something, a repository where you want to get your labels (copy) or a local json file (import).

That's why I talk about an option for this commands :

```
glm -s update import <repo-name> <path-to-json-file>
glm -s update copy <origin-repo-name> <destination-repo-name>
```

That was my first idea when I saw your issue, but with your example, we could imagine a new command :

```
glm update <repo-name> <repo-name--or--path-to-json-file>
```

I'm not a fan of the last one because we have to create a new command for something we could improve to the two previous one...

Last point, maybe the default strategy should be update and not replace.

```
#By default without -s we do an update
glm -s replace import <repo-name> <path-to-json-file>
glm -s replace copy <origin-repo-name> <destination-repo-name>
```

**Comment by negebauer** [comment]
I believe 

```
#By default without -s we do an update
glm -s replace import <repo-name> <path-to-json-file>
glm -s replace copy <origin-repo-name> <destination-repo-name>
```

Would be the perfect solution

**Comment by julien-vidal** [comment]
Awesome ! I'll try to add it when I have some time !
Thanks for your feedback !

**Comment by negebauer** [comment]
Great!
